
FROM maven:3.9.9 AS common-build

WORKDIR /build

# Kopiere die gesamte Projektstruktur
COPY ../pom.xml .  
COPY ../common /common  
COPY ../insure-premium-service /insure-premium-service

# Baue das Common-Projekt
RUN mvn clean install -pl common --also-make


FROM maven:3.9. AS insure-premium-service-build

WORKDIR /insure-premium-service


COPY ../insure-premium-service /insure-premium-service


COPY --from=common-build /common/target/*.jar /insure-premium-service/lib/


RUN mvn clean package


FROM openjdk:23

WORKDIR /app


COPY --from=insure-premium-service-build /insure-premium-service/target/*.jar /app/InsurePremiumApplication.jar

EXPOSE 8081

CMD ["java", "-jar", "InsurePremiumApplication.jar"]

