FROM maven:3.9.9-openjdk-23-slim AS build


WORKDIR /insure-premium-service


COPY pom.xml .


RUN mvn clean install

# copy code
COPY . .

# create jar
RUN mvn clean package

FROM openjdk:23


WORKDIR /

# buld jars
COPY --from=build /insure-premium-service/target/*.jar InsurePremiumApplication.jar

EXPOSE 8081

# start app
CMD ["java", "-jar", "InsurePremiumApplication.jar"]
