RUN mvn clean install

COPY ./ ./ 

RUN mvn clean package

FROM openjdk:23


WORKDIR /

# buld jars
COPY target/*.jar InsurePremiumApplication.jar

EXPOSE 8081

# start app
CMD ["java", "-jar", "InsurePremiumApplication.jar"]
