
FROM maven:3.9.9-openjdk-23-slim AS build


WORKDIR /premium-calculator


COPY pom.xml .


RUN mvn clean install

# copy code
COPY . .

# create jar
RUN mvn clean package

FROM openjdk:23


WORKDIR /

# buld jars
COPY --from=build /premium-calculator/target/*.jar PremiumCalculatorApplication.jar

EXPOSE 8080

# start app
CMD ["java", "-jar", "PremiumCalculatorApplication.jar"]
