# build common lib
FROM maven:3.9.9 AS common-build


WORKDIR /build


COPY ../pom.xml .  
COPY ../common /common  
COPY ../premium-calculator /premium-calculator

RUN mvn clean install -pl common --also-make


FROM maven:3.9.9 AS premium-calculator-build

WORKDIR /premium-calculator


COPY ../premium-calculator /premium-calculator


COPY --from=common-build /common/target/*.jar /premium-calculator/lib/

# build Premium-Calculator
RUN mvn clean package


FROM openjdk:23-slim

WORKDIR /app

# copy jar
COPY --from=premium-calculator-build /premium-calculator/target/*.jar /app/PremiumCalculatorApplication.jar


EXPOSE 8080


CMD ["java", "-jar", "PremiumCalculatorApplication.jar"]
